### ISSUE TITLE
Group creation & coordination for the u-bahn

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#137] opened 2017-11-09 12:28 UTC

**Comment by nshockey** [comment] 2017-11-09 14:23
Possible u-bahn leaders marked in far right column of decisions sheet here: https://docs.google.com/spreadsheets/d/1LnycufwfLumVfEB00Knlfd6yZUQNCLW_CAX6idW78-Q/edit#gid=0&fvid=2112835283

**Comment by JosephMcArthur** [comment] 2017-11-09 14:23
- [ ] @lorrainechu3n to send a note to people on the list above

**Comment by char-siuu-bao** [comment] 2017-11-09 14:23
i have instruction email text from last year that we can modify to email out to walking leaders: 

Hi everyone,

Thank you so much for volunteering to help out with guiding participants to the venue over the next few days! I realize this was a last minute request, and we are very grateful for your assistance. We're hoping it will be pretty simple - here's what you need to know for Saturday and Sunday: 
Collect groups of participants at the hotel lobby starting at around 8:00 AM, and plan to leave at around 8:15.  The metro is under construction so we're asking people to leave on time to anticipate transit delays.  We're aiming for you to each guide groups of 11. 
Once you have collected 11 participants, you can go on your way. We anticipate that some groups will leave later than others as participants come down to the lobby at various times.  If you are one of the last groups to leave it's possible you'll have less than 11 participants. 
Registration (and coffee!) starts at 8:30 AM, and OpenCon programming officially starts at 9:30 AM. 
Detailed directions (with photos) are also on the logistics page. I've attached a print-able PDF of our logistics page to this e-mail as well (directions to the venue start at page 6). If it's helpful, you can also refer to the  google map directions of how to get to American University Washington College of Law by metro.  

Monday will be similar but the venue will be different for the Advocacy Day.  Just getting a few details finalized, but I will send you those directions on Sunday at the latest!

In case of an emergency, you can contact Nick (number) or Nicole (number)

If any of this is unclear please shoot me an e-mail. Thank you again for all of your help,

Lorraine

**Comment by JosephMcArthur** [comment] 2017-11-09 14:23
- [ ] me to post public transit help in logistics email

**Comment by JosephMcArthur** [comment] 2017-11-09 14:24
- [ ] decide someone to stay at the hotel

**Comment by char-siuu-bao** [comment] 2017-11-09 14:24
Hi <<name>>!

Hope you had a smooth trip to DC! Can I ask you for a really last minute favour? We need a few more volunteers to help out with guiding groups of participants from the hotel to the conference venues this weekend. If you can let me know as soon as possible if you could help out with this that would be amazingly helpful. 

Understand if you're not comfortable doing this, but if you could just let me know as soon as possible either way, that would be great! If you're happy to help out with it, I'll send you more details this evening. 

Looking forward to meeting you! 

Best,
Lorraine

**Comment by JosephMcArthur** [comment] 2017-11-09 14:25
* groups of 8-10 for 122 people. 

At least 15.

**Comment by JosephMcArthur** [comment] 2017-11-09 14:26
- [ ] shawn to test instructions.

**Comment by char-siuu-bao** [comment] 2017-11-09 15:24
Will reach out to find caboose

**Comment by char-siuu-bao** [comment] 2017-11-10 17:08
We have 14 confirmed leaders for Day 1 (and more for Day 2 and 3 - because of those with delayed flights) - if each take 9-11, that will definitely cover all hotel attendees plus anyone coming to hotel first (i don't think there will be taht many).
Leaders are: 

Achintya
Vinodh
Luc
Tony
Katerina
Asura
Vinodh
Amie
Laura
Chris F
Linda L
Marcel
Josie
Zoe

Slobodan and Jessica from the OC are the cabooses. Closing for now.

**Closed as completed by char-siuu-bao** 2017-11-10 17:08 UTC
Labels: MVP
